service: serverless

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ${env:AWS_REGION}

functions:
  app:
    handler: index.handler
    events:
      - http:
        path: /schedules
        method: post

resources:
  Resources:
    database:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 20
        DBInstanceClass: db.t2.micro
        Engine: postgres
        MasterUsername:
          Ref: ${env:DB_USERNAME}
        MasterUserPassword:
          Ref: ${env:DB_PASSWORD}
